@startuml
node "KairosNode" {
  port 443
  () "transfer"
  () "verify"
  () "deposit"
  () "withdraw"
  () "getBalance"
  () "getTransactions"
}

node "Prover" {
  () "prove"
  () "verify" as pVerify
  () "batchProve"
  () "batchVerify"
}

database "Database - primary" {
  folder "Balances" {
  }
  folder "Transactions" {
  }
}
database "Database - standby 1" {
}
database "Database - standby 2" {
}
cloud "Casper Blockchain" {
  [VerifierContract]
  [KairosStateContract]
}

"KairosCli" --> "443"

"transfer"  --> "Prover"
"transfer"  --> "Database - primary"
"transfer"  --> "KairosStateContract"


"deposit"  --> "KairosStateContract"
"deposit"  --> "Database - primary"

"withdraw"  --> "KairosStateContract"
"withdraw"  --> "Database - primary"

"verify" --> "Prover"

"getBalance"  --> "Database - primary"

"getTransactions"  --> "Database - primary"

"Database - primary" --> "Database - standby 1"
"Database - primary" --> "Database - standby 2"

"KairosStateContract" --> "VerifierContract"
@enduml
