@startuml
node "CLI" {
}

node "L2 Node" {
  [L1 SDK]
  port 443
  () "transfer"
  () "verify"
  () "deposit"
  () "withdraw"
  () "getBalance"
  () "getTransactions"
}

node "Prover" {
  port 443 as proverPort
  () "batchProve"
  () "batchVerify"
}

database "Data store - primary" {
  folder "Balances" {
  }
  folder "Transactions" {
  }
}
database "Data store - standby 1" {
}
database "Data store - standby 2" {
}
cloud "L1" {
  [VerifierContract]
  [StateContract]
}

"CLI" --> "443"

"transfer"  --> "proverPort"
"transfer"  --> "Data store - primary"
"transfer"  --> "L1 SDK"


"deposit"  --> "L1 SDK"
"deposit"  --> "Data store - primary"

"withdraw"  --> "L1 SDK"
"withdraw"  --> "Data store - primary"

"verify" --> "proverPort"

"getBalance"  --> "Data store - primary"

"getTransactions"  --> "Data store - primary"

"Data store - primary" --> "Data store - standby 1"
"Data store - primary" --> "Data store - standby 2"

"L1 SDK" --> L1
"StateContract" --> "VerifierContract"
@enduml
