@startuml
autoactivate on
actor "Bob :: User" as Bob
box "L2-stack" #LightBlue
participant KairosCli
participant CasperCli
participant KairosNode
participant Database
participant Prover
participant CasperNode
end box
box "on-chain" #LightGreen
participant DepositSession
participant KairosStateContract
end box

activate CasperNode
activate KairosNode

note over CasperNode, DepositSession
At some point the deploy gets executed on-chain.
end note

CasperNode -> DepositSession: call()
DepositSession -> KairosStateContract: verify_deposit_entrypoint(\n\tnew_account_balance,\n\told_accout_balance,\n\tnew_account_balances_root_hash,\n\tsibling_hashes,\n\tuser,\n\tamount\n)
note over KairosStateContract, KairosStateContract
if ok then
end note
KairosStateContract -> KairosStateContract: update_state_entrypoint(new_account_balances_root_hash)
KairosStateContract --> KairosStateContract: Ok
KairosStateContract --> DepositSession: Ok 
DepositSession -> DepositSession: transfer_from_purse_to_purse(user_purse, kairos_purse, amount)
DepositSession --> DepositSession: Ok
DepositSession --> CasperNode: end call()
@enduml
