@startuml
autoactivate on
actor "Bob :: User" as Bob
box "L2-stack" #LightBlue
participant ClientCli
participant L1Sdk
participant L2Node
participant DataStore
participant Prover
participant L1Node
end box
box "on-chain" #LightGreen
participant DepositSession
participant StateContract
end box

activate L1Node
activate L2Node

note over L1Node, DepositSession
At some point the deploy gets executed on-chain.
end note

L1Node -> DepositSession: call()
DepositSession -> StateContract: verify_deposit_entrypoint(\n\tupdated_account_balances_root_hash,\n\tupdate_metadata,\n\tdepositor,\n\tamount,\n\ttoken_id\n)
note over StateContract, StateContract
if ok then
end note
StateContract -> StateContract: update_state_entrypoint(\n\tupdated_account_balances_root_hash\n)
StateContract --> StateContract: Ok
StateContract --> DepositSession: Ok 
DepositSession -> DepositSession: transfer_from_purse_to_purse(\n\tdepositor_purse,\n\tsystem_purse,\n\tamount,\n\ttoken_id\n)
DepositSession --> DepositSession: Ok
DepositSession --> L1Node: end call()
@enduml
