@startuml
autoactivate on
actor "Bob :: User" as Bob
box "L2-stack" #LightBlue
participant ClientCli
participant L1Sdk
participant L2Node
participant DataStore
participant Prover
participant L1Node
end box
box "on-chain" #LightGreen
participant DepositSession
participant StateContract
end box

activate L1Node
activate L2Node

note over L1Node, L2Node
After the deploy gets processed we get notified
end note

L1Node -> L2Node: eventHandler(event :: OnDeployProcessed)
L2Node -> L1Node: query_balance()
L1Node --> L2Node: query_balance_result

L2Node -> DataStore: insert_deposit(user: Bob, amount, token_id)
DataStore --> L2Node: Ok
L2Node --> L2Node: end eventHandler

note over ClientCli, L2Node
After sufficient time the user can query the balance
end note
Bob -> ClientCli: get_balance
ClientCli -> L2Node: get_balance(user: Bob)
L2Node -> DataStore: get_balance(user: Bob)
DataStore --> L2Node: balance
L2Node --> ClientCli: balance
ClientCli --> Bob: balance

@enduml
