@startuml
autoactivate on
actor "Bob :: User" as Bob
box "L2-stack" #LightBlue
participant ClientCli
participant L1Sdk
participant L2Node
participant DataStore
participant Prover
participant L1Node
end box
box "on-chain" #LightGreen
participant DepositSession
participant StateContract
end box

activate L1Node
activate L2Node

L2Node -> L1Node: subscribe(OnDeployProcessed)
Bob -> ClientCli: deposit(depositor: Bob, amount, token_id, key_pair)
ClientCli -> L2Node: deposit(depositor: Bob, amount, token_id)

L2Node -> L2Node: update_merkle_tree(depositor, amount, token_id)
L2Node --> L2Node: (updated_account_balances_root_hash,\n update_metadata)
note over L2Node, L2Node
What we create here is a deploy that will execute the deposit session.
In the session we check whether the token amount in the transaction
is equal to the amount that was used to create the updated_account_balance_root_hash.
Moreover, we use the VerifyContract to check whether the Merkle-tree update
was done correctly. See deposit sequence diagram - deploy execution
end note
L2Node -> L2Node: create_deposit_deploy(\n\tupdated_account_balance_root_hash,\n\tupdate_metadata,\n\tdepositor,\n\tamount\n\ttoken_id\n)
L2Node --> L2Node: deposit_deploy :: Deploy
L2Node --> ClientCli: deposit_deploy :: Deploy

ClientCli -> L1Sdk: sign_deploy(deposit_deploy, secret_key)
L1Sdk --> ClientCli: signed_deposit_deploy :: SignedDeploy

ClientCli -> L2Node: /deploy/forward/(signed_deposit_deploy :: SignedDeploy)
L2Node -> L1Node: account_put_deploy(signed_verify_deposit_deploy :: SignedDeploy)
L1Node --> L2Node: account_put_deploy_result
L2Node --> ClientCli: account_put_deploy_result
ClientCli --> Bob: account_put_deploy_result
@enduml
