@startuml
autoactivate on
actor "Bob :: User" as Bob
box "L2-stack" #LightBlue
participant KairosCli
participant CasperCli
participant KairosNode
participant Database
participant Prover
participant CasperNode
end box
box "on-chain" #LightGreen
participant DepositSession
participant KairosStateContract
end box

activate CasperNode
activate KairosNode

note over CasperNode, KairosNode
After the deploy gets processed we get notified
end note

CasperNode -> KairosNode: eventHandler(event :: DeployProcessed)
KairosNode -> CasperNode: query_balance()
CasperNode --> KairosNode: query_balance_result

KairosNode -> Database: insert_deposit(user: Bob, amount)
Database --> KairosNode: Ok

note over KairosCli, KairosNode
After sufficient time the user can query the balance
end note
Bob -> KairosCli: get_balance
KairosCli -> KairosNode: GET /balance/{user: Bob}
KairosNode -> Database: get_balance(user: Bob)
Database --> KairosNode: balance
KairosNode --> KairosCli: balance
KairosCli --> Bob: balance

@enduml
