@startuml
autoactivate on
actor "Bob :: User" as Bob
box "L2-stack" #LightBlue
participant KairosCli
participant CasperCli
participant KairosNode
participant CasperCliBackend
participant Database
participant Prover
participant CasperNode
end box
box "on-chain" #LightGreen
participant TransferSession
participant KairosStateContract
end box

activate CasperNode
activate KairosNode

KairosNode -> CasperNode: subscribe(DeployProcessed)
Bob -> KairosCli: transfer(from: Bob, to: Alice, amount, key_pair)

note over KairosCli, KairosNode
This happens multiple times
for different users,
the KairosNode optimizes transfers
end note 

KairosCli -> KairosNode: POST /transfer/{user: Bob, user: Alice, amount, signature, public_key}
KairosNode -> KairosNode: verify_signature
KairosNode --> KairosNode: Ok
KairosNode --> KairosCli: Ok
KairosCli --> Bob: Ok
@enduml
