@startuml
autoactivate on
actor "Bob :: User" as Bob
box "L2-stack" #LightBlue
participant ClientCli
participant L1Sdk
participant L2Node
participant DataStore
participant Prover
participant L1Node
end box
box "on-chain" #LightGreen
participant TransferSession
participant StateContract
end box

activate L1Node
activate L2Node

L2Node -> L1Node: subscribe(DeployProcessed)
Bob -> ClientCli: transfer(Amount, TokenId, sender :: KeyPair, receiver :: PubKey)

note over ClientCli, L2Node
This happens multiple times for different users.
end note 

ClientCli -> L2Node: transfer(sender :: PubKey, recipient :: PubKey, Amount, TokenId, Signature)
L2Node -> L2Node: verify_signature(sender :: PubKey, Signature)
L2Node --> L2Node: Ok
L2Node -> DataStore: add_transaction_to_next_batch(transfer.into::<Transaction>())
DataStore --> L2Node: Ok
L2Node --> ClientCli: Ok
ClientCli --> Bob: Ok

@enduml
