@startuml
autoactivate on
actor "Bob :: User" as Bob
box "L2-stack" #LightBlue
participant ClientCli
participant L1Sdk
participant L2Node
participant DataStore
participant Prover
participant L1Node
end box
box "on-chain" #LightGreen
participant TransferSession
participant StateContract
end box

activate L1Node
activate L2Node

note over L1Node, TransferSession
At some point the deploy gets executed on-chain.
end note

L1Node -> TransferSession: call()

note over TransferSession, StateContract
This is where we verify the proof,
we obviously need to provide the public inputs
end note

TransferSession -> StateContract: verify_transfer_entrypoint(\n\tupdated_account_balances_root_hash,\n\tproof,\n\tVector<{sender, receiver, amount, token_id}\n)

note over StateContract, StateContract
If proof is Ok then
end note
StateContract -> StateContract: update_state_entrypoint(updated_account_balances_root_hash)
StateContract --> StateContract: Ok
StateContract --> TransferSession: Ok 
TransferSession --> L1Node: end call()
@enduml
