@startuml
autoactivate on
actor "Bob :: User" as Bob
box "L2-stack" #LightBlue
participant KairosCli
participant CasperCli
participant KairosNode
participant CasperCliBackend
participant Database
participant Prover
participant CasperNode
end box
box "on-chain" #LightGreen
participant TransferSession
participant KairosStateContract
end box

activate CasperNode
activate KairosNode

note over CasperNode, KairosNode
After the deploy gets processed we get notified
end note

CasperNode -> KairosNode: eventHandler(event :: DeployProcessed)
KairosNode -> Database: insert_transfers(Vector<{sender, receiver, amount}>)
Database --> KairosNode: Ok
KairosNode --> KairosNode: end eventHandler

note over KairosCli, KairosNode
After sufficient time the user can query the balance
end note
Bob -> KairosCli: get_balance
KairosCli -> KairosNode: GET /balance/{user: Bob}
KairosNode -> Database: get_balance(user: Bob)
Database --> KairosNode: balance
KairosNode --> KairosCli: balance
KairosCli --> Bob: balance


@enduml
