@startuml
autoactivate on
actor "Bob :: User" as Bob
box "L2-stack" #LightBlue
participant KairosCli
participant CasperCli
participant KairosNode
participant CasperCliBackend
participant Database
participant Prover
participant CasperNode
end box
box "on-chain" #LightGreen
participant TransferSession
participant KairosStateContract
end box

activate CasperNode
activate KairosNode

note over CasperNode, TransferSession
At some point the deploy gets executed on-chain.
end note

CasperNode -> TransferSession: call()

note over TransferSession, KairosStateContract
This is where we verify the proof,
we obviously need to provide the public inputs
end note

TransferSession -> KairosStateContract: verify_transfer_entrypoint(\n\tnew_account_balances_root_hash,\n\tproof,\n\tVector<{sender, receiver, amount}\n)

note over KairosStateContract, KairosStateContract
If proof is Ok then
end note
KairosStateContract -> KairosStateContract: update_state_entrypoint(new_account_balances_root_hash)
KairosStateContract --> KairosStateContract: Ok
KairosStateContract --> TransferSession: Ok 
TransferSession --> CasperNode: end call()
@enduml
