@startuml
autoactivate on
actor "Bob :: User" as Bob
box "L2-stack" #LightBlue
participant ClientCli
participant L1Sdk
participant L2Node
participant DataStore
participant Prover
participant L1Node
end box
box "on-chain" #LightGreen
participant TransferSession
participant StateContract
end box

activate L1Node
activate L2Node

L2Node -> L1Node: subscribe(OnDeployProcessed)
Bob -> ClientCli: transfer(sender: Bob, recipient: Alice, amount, token_id, key_pair)

note over ClientCli, L2Node
This happens multiple times
for different users,
the L2Node optimizes transfers
end note 

ClientCli -> L2Node: transfer(sender: Bob, recipient: Alice, amount, token_id, signature, public_key)
L2Node -> L2Node: verify_signature
L2Node --> L2Node: Ok
L2Node --> ClientCli: Ok
ClientCli --> Bob: Ok
@enduml
