erDiagram
    WebClient }o--|| ApiServer : connect-to
    
    CliClient }o--|| ApiServer : connect-to

    ApiServer {
        fn deposit()
        fn withdraw()
        fn transfer()
        fn getBalance()
        fn getBalances()
        fn getTransactions()
    }

    ApiServer ||--|| Database : read-write-to

    ApiServer ||--|| Prover : use

    Prover {
        fn proveDeposit()
        fn proveWithdrawal()
        fn proveTransfer()
        fn proveRollup()
        fn verifyDeposit()
        fn verifyWithdrawal()
        fn verifyTransfer()
        fn verifyRollup()
    }

    ValidiumStateContract {
        fn getState()
        fn updateState()
    }

    ApiServer ||--|| CardanoNode : submit-read-and-notify
    CardanoNode ||--|| ValidiumStateContract : submit-and-read

    ValidiumStateContract ||--|| VerifierContract : request-verification
