erDiagram
    WebClient }o--|| ApiServer : connect-to
    
    CliClient }o--|| ApiServer : connect-to

    ApiServer {
        fn deposit()
        fn withdraw()
        fn transfer()
        fn getBalance()
        fn getTransactions()
    }

    ApiServer ||--|| Database : read-write-to

    ApiServer ||--|| Proover : use

    Proover {
        fn proove()
        fn verify()
    }

    ApiServer ||--|| ValidiumStateContract : use

    ValidiumStateContract {
        fn getState()
        fn updateState()
    }

    Proover ||--|| VerifierContract : use
    VerifierContract {
    }

    VerifierContract ||--|| ValidiumStateContract : notify
